on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build
